export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
  JUMMAH = 'JUMMAH',
}

export enum USER_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  RESTRICTED = 'RESTRICTED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETE',
}

export enum SUBSCRIPTION_TIER {
  FREE = 'FREE',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SUBSCRIPTION_STATUS {
  NONE = 'NONE',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
}
